#include "api_grid_test_common.h"

using namespace api_grid_test;

namespace {

// Global host reference for a matrix generated by base_value(i,j).
inline std::vector<Complex> make_global(int m, int n, Complex (*value)(int, int))
{
    std::vector<Complex> G(static_cast<size_t>(m) * n);
    for(int i = 0; i < m; ++i)
        for(int j = 0; j < n; ++j)
            G[static_cast<size_t>(i) * n + j] = value(i, j);
    return G;
}

// Apply the pivot permutation to a global host matrix, mirroring plapiv:
// P(k) swaps row/col k with row/col g_ipiv[k]-1; forward applies k ascending,
// backward descending.  Returns the permuted global matrix.
inline std::vector<Complex> apply_pivots_host(const std::vector<Complex>& G,
                                              int m, int n, char direc, char rowcol,
                                              const std::vector<int>& g_ipiv)
{
    std::vector<Complex> R = G;
    const int begin = (direc == 'F') ? 0 : m - 2;
    const int end   = (direc == 'F') ? m - 1 : -1;
    const int step  = (direc == 'F') ? 1 : -1;
    for(int k = begin; k != end; k += step){
        const int target = g_ipiv[k] - 1;
        if(target == k) continue;
        if(rowcol == 'C'){
            // Swapping columns k and target moves the fixed segment length n
            // (rows) of each column -- mirror plapiv's n = segment length.
            for(int i = 0; i < n; ++i)
                std::swap(R[static_cast<size_t>(i) * n + k],
                          R[static_cast<size_t>(i) * n + target]);
        }else{
            for(int j = 0; j < n; ++j)
                std::swap(R[static_cast<size_t>(k) * n + j],
                          R[static_cast<size_t>(target) * n + j]);
        }
    }
    return R;
}

// Global pivot vector for the fixed permutation that swaps (0,m-1) and
// (1,m-2); the rest are identity.  g_ipiv[k] is the 1-based target for step k.
inline std::vector<int> make_g_ipiv(int m)
{
    std::vector<int> g_ipiv(m);
    for(int k = 0; k < m; ++k){
        if(k == 0)      g_ipiv[k] = m;
        else if(k == 1) g_ipiv[k] = m - 1;
        else            g_ipiv[k] = k + 1;
    }
    return g_ipiv;
}

// Fill the distributed ipiv array from the global pivot vector: the local
// entry on the owning process holds g_ipiv[k] (1-based) for its global row k.
inline void fill_ipiv(const ddla::DdlaHandle_t& handle, std::vector<int>& ipiv, const int* desc,
                      const std::vector<int>& g_ipiv)
{
    for(int iloc = 0; iloc < ddla_test::m_loc(handle, desc); ++iloc){
        const int k = indx_l2g_r(desc, handle, iloc);
        ipiv[iloc] = g_ipiv[k];
    }
}

inline void check_one_case(const ddla::DdlaHandle_t& handle, const int* desc,
                           int m, int n, char direc, char rowcol,
                           Complex (*value)(int, int), double tol)
{
    const std::string name = std::string("plapiv(handle, ") + direc + "," + rowcol + ",C)";
    const std::vector<int> g_ipiv = make_g_ipiv(m);
    std::vector<int> ipiv(ddla_test::m_loc(handle, desc), 0);
    fill_ipiv(handle, ipiv, desc, g_ipiv);

    const auto h_A = make_local<Complex>(handle, desc, value);
    DeviceBuffer<Complex> d_A(handle, h_A.size());
    upload(handle, d_A.ptr, h_A);
    check_ddla_sync(handle);

    ddla::plapiv(handle, direc, rowcol, 'C', m, n, d_A.ptr, desc, ipiv.data(), desc, nullptr);
    auto out = download(handle, d_A.ptr, h_A.size());

    const auto G = make_global(m, n, value);
    const auto R = apply_pivots_host(G, m, n, direc, rowcol, g_ipiv);

    double err = 0.0;
    for(int jloc = 0; jloc < ddla_test::n_loc(handle, desc); ++jloc){
        const int j = indx_l2g_c(desc, handle, jloc);
        if(j >= n) continue;
        for(int iloc = 0; iloc < ddla_test::m_loc(handle, desc); ++iloc){
            const int i = indx_l2g_r(desc, handle, iloc);
            if(i >= m) continue;
            err = std::max(err, static_cast<double>(
                std::abs(out[iloc + jloc * desc[DDLA_LLD_]] - R[static_cast<size_t>(i) * n + j])));
        }
    }
    require_close(handle, name, err, tol);
}

// Regression for the rowcol='C' segment length: with m pivots over columns of
// an n_seg x m matrix (n_seg < m, e.g. pgetrs side='R' where B is nrhs x n),
// each swapped column moves only the leading n_seg rows.  The device segment
// length must be num_loc(n_seg, ...), NOT num_loc(m, ...).
inline void check_nonsquare_col(const ddla::DdlaHandle_t& handle,
                                int m, int n_seg, int nb, char direc,
                                Complex (*value)(int, int), double tol)
{
    const std::string name = std::string("plapiv(handle, ") + direc + ",C,C) n_seg=" +
                             std::to_string(n_seg) + " != m=" + std::to_string(m);
    int descB[ddla::DDLA_DLEN_];
    DDLA_CHECK(ddlaDescInit(descB, handle, n_seg, m, nb, nb, 0, 0));
    int descIP[ddla::DDLA_DLEN_];
    DDLA_CHECK(ddlaDescInit(descIP, handle, m, m, nb, nb, 0, 0));

    const std::vector<int> g_ipiv = make_g_ipiv(m);
    std::vector<int> ipiv(ddla_test::m_loc(handle, descIP), 0);
    fill_ipiv(handle, ipiv, descIP, g_ipiv);

    const auto h_B = make_local<Complex>(handle, descB, value);
    DeviceBuffer<Complex> d_B(handle, h_B.size());
    upload(handle, d_B.ptr, h_B);
    check_ddla_sync(handle);

    ddla::plapiv(handle, direc, 'C', 'C', m, n_seg, d_B.ptr, descB, ipiv.data(), descIP, nullptr);
    auto out = download(handle, d_B.ptr, h_B.size());

    // Global column-swap reference over the n_seg x m matrix (row-major).
    std::vector<Complex> G(static_cast<size_t>(n_seg) * m, Complex(0, 0));
    for(int i = 0; i < n_seg; ++i)
        for(int j = 0; j < m; ++j)
            G[static_cast<size_t>(i) * m + j] = value(i, j);
    const int begin = (direc == 'F') ? 0 : m - 2;
    const int end   = (direc == 'F') ? m - 1 : -1;
    const int step  = (direc == 'F') ? 1 : -1;
    for(int k = begin; k != end; k += step){
        const int target = g_ipiv[k] - 1;
        if(target == k) continue;
        for(int i = 0; i < n_seg; ++i)
            std::swap(G[static_cast<size_t>(i) * m + k],
                      G[static_cast<size_t>(i) * m + target]);
    }

    double err = 0.0;
    for(int jloc = 0; jloc < ddla_test::n_loc(handle, descB); ++jloc){
        const int j = indx_l2g_c(descB, handle, jloc);
        for(int iloc = 0; iloc < ddla_test::m_loc(handle, descB); ++iloc){
            const int i = indx_l2g_r(descB, handle, iloc);
            err = std::max(err, static_cast<double>(
                std::abs(out[iloc + jloc * descB[DDLA_LLD_]] - G[static_cast<size_t>(i) * m + j])));
        }
    }
    require_close(handle, name, err, tol);
}

} // namespace

void check_plapiv(const ddla::DdlaHandle_t& handle, const Shape& base)
{
    const int nb = base.nb;
    int nprows = 0, npcols = 0;
    ddlaGetGridDims(handle, nprows, npcols);
    // Use a square matrix so the pivot count m equals both the number of rows
    // and columns: the pivot vector (distributed by rows of the descriptor)
    // has one entry per pivot in both the 'R' and 'C' cases.
    const int m = round_up_for_grid(base.m, nb, std::max(nprows, npcols));
    int desc[ddla::DDLA_DLEN_];
    DDLA_CHECK(ddlaDescInit(desc, handle, m, m, nb, nb, 0, 0));

    auto value = [](int i, int j){ return Complex(10.0 * i + j, -0.5 * i + 0.25 * j); };

    // (direc, rowcol, m-pivots, n-segment)
    check_one_case(handle, desc, m, m, 'F', 'R', value, 1e-12);
    check_one_case(handle, desc, m, m, 'B', 'R', value, 1e-12);
    check_one_case(handle, desc, m, m, 'F', 'C', value, 1e-12);
    check_one_case(handle, desc, m, m, 'B', 'C', value, 1e-12);

    // Non-square leading-block segment (rowcol='C'): B is n_seg x m with
    // n_seg < m -- the pgetrs side='R' shape.  Regression-covers the
    // length_rowcol_C fix (segment must be num_loc(n_seg), not num_loc(m)).
    // n_seg = nb*nprows guarantees every rank owns a non-zero local row block,
    // so the pivot exchange never issues a zero-length NCCL/MPI transfer.
    const int n_seg = nb * nprows;
    check_nonsquare_col(handle, m, n_seg, nb, 'F', value, 1e-12);
    check_nonsquare_col(handle, m, n_seg, nb, 'B', value, 1e-12);
}

int main(int argc, char** argv)
{
    return run_grid_test(argc, argv, "test_api_grid_plapiv", check_plapiv);
}
